name: Demo of build an deploy

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

env:
  APP_NAME: "gh-fudge"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      - name: Build and Publish
        run: |
          dotnet restore
          dotnet build --no-restore
          dotnet test
          dotnet publish -c Release -o ./out

      - name: Upload to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: ./out

  deploy:
    runs-on: "ubuntu-latest"
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Get app
        uses: actions/download-artifact@v2
        with:
          name: app
          path: ./out

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: Push Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.APP_NAME}}
          package: ./out
