
name: Demo of build an deploy

on:
  push:
    branches: [main, dev]
  workflow_dispatch:

 jobs:
   build:
     runs-on: 'ubuntu-latest'
     steps:
       - run: |
           echo 'hello'

             

